# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - tros_arm_controller

  tros_arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_turret_joint
      - arm_base_turret_joint
      - arm_mid_joint
      - arm_end_effector_turn_joint
      - arm_end_effector_spin_joint